FROM python:3.11-slim

WORKDIR /app

COPY accel_ai_service.py .
COPY ai_model_super_advanced.py .
COPY build_hourly_features_and_alerts.py .

RUN pip install --no-cache-dir pandas numpy scikit-learn mysql-connector-python

CMD ["python", "-u", "accel_ai_service.py"]
